-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 18:34:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lag` ;
USE `lag` ;

-- -----------------------------------------------------
-- Table `lag`.`usuarios_internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lag`.`usuarios_internos` (
  `idusuarios_internos` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NULL,
  `chat_id` VARCHAR(45) NULL,
  `unique_code` VARCHAR(45) NULL,
  `qrcode` VARCHAR(255) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios_internos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lag`.`pagos_internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lag`.`pagos_internos` (
  `idpagos_internos` INT NOT NULL AUTO_INCREMENT,
  `idusuarios_internos` INT NULL,
  `monto` INT NULL,
  PRIMARY KEY (`idpagos_internos`),
  INDEX `usuariosInternos_idx` (`idusuarios_internos` ASC),
  CONSTRAINT `usuariosInternos`
    FOREIGN KEY (`idusuarios_internos`)
    REFERENCES `lag`.`usuarios_internos` (`idusuarios_internos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lag`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lag`.`asientos` (
  `idasientos` INT NOT NULL AUTO_INCREMENT,
  `zona` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `usuario` VARCHAR(255) NULL,
  PRIMARY KEY (`idasientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lag`.`internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lag`.`internos` (
  `idinternos` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idinternos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lag`.`usuarios_externos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lag`.`usuarios_externos` (
  `idusuarios_externos` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `chat_id` VARCHAR(45) NULL,
  `unique_code` VARCHAR(45) NULL,
  `qrcode` VARCHAR(255) NULL,
  `password` VARCHAR(45) NULL,
  `qrcodeimage` VARCHAR(255) NULL,
  PRIMARY KEY (`idusuarios_externos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lag`.`pagos_externos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lag`.`pagos_externos` (
  `idpagos_externos` INT NOT NULL AUTO_INCREMENT,
  `idusuarios_externos` INT NULL,
  `monto` INT NULL,
  PRIMARY KEY (`idpagos_externos`),
  INDEX `usuariosExternos_idx` (`idusuarios_externos` ASC),
  CONSTRAINT `usuariosExternos`
    FOREIGN KEY (`idusuarios_externos`)
    REFERENCES `lag`.`usuarios_externos` (`idusuarios_externos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
